imports:
    - { resource: config_dev.yml }

locale.options:
    default: en

dbs.options:
    mysql_social:
        driver: pdo_sqlite
        path: %app_root_dir%/../var/cache/social_data.db
    mysql_brain:
        driver: pdo_sqlite
        path: %app_root_dir%/../var/cache/brain_data.db

neo4j.options:
    host: %db.neo4j.testing.host%
    port: %db.neo4j.testing.port%
    auth: %db.neo4j.testing.auth%
    user: %db.neo4j.testing.user%
    pass: %db.neo4j.testing.pass%

swiftmailer.options:
    disable_delivery: true
